version: '3.8'

x-base-service:
  &base-service
  tty: true
  stdin_open: true
  command: make boot-startup
  working_dir: /app

services:
  ###################
  # Back end services
  api:
    &api
    <<: *base-service
    build:
      context: ./backend-estrangeum
      dockerfile: Dockerfile.development
    ports:
      - 4000:4000
    volumes:
      - ./backend-estrangeum:/app:cached
    depends_on:
      - postgres15

  ####################
  # Front end services
  web:
    &web
    <<: *base-service
    build:
      context: ./frontend-estrangeum
      dockerfile: Dockerfile.development
    ports:
      - 3333:3333
    volumes:
      - ./frontend-estrangeum:/app:cached
    depends_on:
      - api

  ###############
  # Public images

  postgres15:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 6432:5432
    volumes:
      - postgres15:/var/lib/postgresql/data:delegated

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 80:80
    volumes:
      - pgadmin4:/root/.pgadmin:delegated
    depends_on:
      - postgres15

volumes:

  # Public images
  postgres15:
  pgadmin4:
